"""Hidden test cases (not shown to the student before grading).

Each entry is a snippet: any statements, then a final expression. The expected value
(its repr plus anything printed) is computed by running the reference solution.
Lines are separated by '; ' only when the snippet is a list item with '\n'.
"""

L = 'Link'

HIDDEN = {
    'fa14-q3-a': ['sixty_ones(Link(6))', 'sixty_ones(Link(1, Link(6)))', 'sixty_ones(Link(6, Link(1, Link(6, Link(1, Link(6, Link(1)))))))', 'sixty_ones(Link(6, Link(6, Link(1, Link(1)))))'],
    'fa14-q3-b': ['no_eleven(0)', 'no_eleven(1)', 'len(no_eleven(6))', 'no_eleven(5)[-3:]'],
    'fa14-q5-a': ['t = slinky([1, 2, 4, 8, 3, 6], lambda x: 2*x)\nstarts(t), [get(t, i) for i in range(6)]',
                  'r = slinky([7, 7, 7], lambda x: x)\nstarts(r), get(r, 2)',
                  'length(slinky([], abs))'],
    'fa15-q3-c': ['print(multiples(3, Link(3, Link(6, Link(7, Link(9))))))', 'print(multiples(2, Link(1)))', 'print(multiples(1, Link(4, Link(5))))'],
    'fa15-q3-e': ['s = int_set([0])\n[s(k) for k in range(5)]', 's = int_set([])\n[s(k) for k in range(4)]',
                  's = int_set([2, 8, 15, 16])\n[k for k in range(20) if s(k)]', 'bits([6])(0)(1)(1)(\'entry\'), bits([6])(1)(1)(\'entry\')'],
    'fa16-q7-a': ['sums(1, 1)', 'sums(3, 2)', 'sums(5, 3)', 'len(sums(6, 4))'],
    'fa16-q7-b': ['sums(1, 1)', 'sums(3, 2)', 'sums(5, 3)', 'len(sums(6, 4))'],
    'fa17-q3-a': ['splice([1, 2], [9], 0)', 'splice([1, 2], [9], 2)', 'splice([], [5, 6], 0)', 'a = [1, 2, 3]\nsplice(a, [0], 1)\na'],
    'fa17-q3-b': ['all_splice([1, 2], [3], [1, 2, 3])', 'all_splice([5], [5], [5, 5])', 'all_splice([1, 2], [3], [3, 2, 1])'],
    'fa17-q3-c': ['print(splink(Link(1, Link(2)), Link(9), 0))', 'print(splink(Link(1, Link(2)), Link(9, Link(8)), 2))',
                  'a, b = Link(1, Link(2, Link(3))), Link(5)\nprint(splink(a, b, 1)); print(a); print(b)'],
    'fa17-q4-a': ['both(Link(1, Link(2, Link(3))), Link(4, Link(5, Link(6))))', 'both(Link(1, Link(2)), Link(1, Link(2)))',
                  'both(Link(5), Link(1, Link(3, Link(5, Link(7)))))', 'both(Link(2, Link(4, Link(6, Link(8)))), Link(1, Link(4, Link(8))))'],
    'fa17-q4-c': ['ways(0, 0, 0, [abs])', 'ways(0, 3, 3, [lambda x: x + 1])', 'ways(1, 16, 4, [lambda x: x * 2, lambda x: x * 4])', 'ways(2, 7, 2, [lambda x: x + 1])'],
    'fa18-q2': ['lowest([5])', 'lowest([-1, 1])', 'lowest([0, 1, 2, -1, 3])', 'lowest([10, -20, 30, -40])'],
    'fa18-q4-a': ['plus(7)', 'plus(12)', 'plus(123)', 'plus(10203)', 'plus(9999)'],
    'fa18-q4-b': ['plusses(5, 6)', 'plusses(5, 5)', 'plusses(1234, 100)', 'plusses(11111, 30)'],
    'fa18-q5-a': ["tally([Poll('X', {'a': 3})], 'b')", "tally([], 'a')", "tally([Poll('X', {'a': 3}), Poll('Y', {'b': 1, 'a': 0})], 'a')"],
    'fa18-q6': ['print(replace(Link(1, Link(2, Link(3))), Link(9), 1, 2))', 'print(replace(Link(1, Link(2, Link(3))), Link(8, Link(9)), 1, 3))',
                'print(replace(Link(1, Link(2, Link(3, Link(4)))), Link(0), 2, 3))'],
    'fa19-q4': ['stable([5], 0, 0)', 'stable([1, 4, 7], 2, 3)', 'stable([1, 4, 7], 2, 5)', 'stable([10, 9, 8, 7], 3, 2)'],
    'fa19-q5-a': ['partitions(3, 3)', 'partitions(3, 1)', 'partitions(5, 3)', 'partitions(0, 2)'],
    'fa19-q6': ['switch([5], [1], 3)', 'switch([1], [5], 0)', 'switch([1], [5], 1)', 'switch([9, 1, 9, 1], [1, 9, 1, 9], 2)', 'switch([9, 1, 9, 1], [1, 9, 1, 9], 3)'],
    'fa20-q2-b': ['print(filter_index(lambda i: i % 2 == 0, Link(5, Link(6, Link(7, Link(8))))))', 'print(filter_index(lambda i: False, Link(1, Link(2))))',
                  'print(filter_index(lambda i: i > 0, Link(4)))'],
    'fa20-q3-a': ['s = sparse_list([7])\ns.n, s.common, s.others', 's = sparse_list([1, 2, 2, 1, 3])\ns.n, s.common, s.others', 's = sparse_list([4, 4, 4])\ns.others'],
    'fa20-q3-b': ['s = sparse_list([1, 2, 2, 3])\n[item(s, i) for i in range(6)]', 'item(sparse_list([9]), 0), item(sparse_list([9]), 1)'],
    'fa20-q3-c': ['items(sparse_list([1, 2, 2, 3]))', 'items(sparse_list([5]))', 'items(sparse_list([0, 0, 1, 0]))'],
    'fa21-q2-a': ['change(0, [1, 2])', 'change(3, [])', 'change(5, [2, 2])', 'change(6, [1, 2, 3])', 'change(9, [4, 4, 1])'],
    'fa21-q2-b': ['amounts([])', 'amounts([1])', 'amounts([1, 1])', 'amounts([3, 4, 5])'],
    'fa21-q4-a': ['snap(lambda x: x, lambda x: True, [])', 'snap(abs, lambda x: x > 2, [-3, 1, 4, -1])',
                  'calls = []\ndef f(x):\n    calls.append(x)\n    return x + 1\nsnap(f, lambda y: y % 2, [1, 2, 3, 4])\ncalls'],
    'fa21-q4-b': ['max_diff([3], abs)', 'max_diff([1, 5, 3], lambda x: -x)', "max_diff(['ab', 'abcd', 'a'], len)"],
    'fa21-q4-c': ['max_diff_fast([3], abs)', 'max_diff_fast([1, 5, 3], lambda x: -x)', "max_diff_fast(['ab', 'abcd', 'a'], len)",
                  'calls = []\ndef f(x):\n    calls.append(x)\n    return x\nmax_diff_fast([4, 1, 7], f)\nlen(calls)'],
    'fa22-q3-b': ['roll_dice(1, make_test_dice([4]))', 'roll_dice(3, make_test_dice([1, 2, 3]))', 'roll_dice(3, make_test_dice([2, 3, 1]))',
                  'd = make_test_dice([2, 3, 1, 5])\nroll_dice(2, d), roll_dice(2, d)'],
    'fa22-q5-a': ['count_subsets([])', 'count_subsets([100])', 'count_subsets([50, 50, 50])', 'count_subsets([10, 90, 60, 40, 100])'],
    'fa22-q6-a': ['destinations([], 0)', 'destinations([(1, 1)], 1)', 'destinations([(2, 3), (1, 2), (2, 1), (2, 3)], 2)'],
    'fa23-q4-a': ['fit(1, 1)', 'fit(2, 1)', 'fit(5, 2)', '[fit(18, n) for n in range(1, 10)]'],
    'fa23-q4-b': ['squares(1, 1)', 'squares(4, 3)', 'squares(13, 2)', 'len(squares(30, 1))'],
    'fa23-q4-b-iv': ['shortest(1)', 'shortest(12)', 'sorted(shortest(13))', 'len(shortest(15))'],
    'fa23-q6-a-b': ['after((), 1, 2)', 'after(Link(1, Link(2)), 1, 2)', 'after(Link(2, Link(1)), 1, 2)',
                    'after(Link(1, Link(1)), 1, 1)', 'after(Link(2, Link(1, Link(3, Link(2)))), 1, 2)'],
    'fa24-q4-a': ['semiperfect(1)', 'semiperfect(6)', 'semiperfect(70)', '[k for k in range(40, 70) if semiperfect(k)]'],
    'fa24-q4-b': ['subsums([], 0)', 'subsums([5], 5)', 'subsums([1, 2, 3], 3)', 'subsums([1, 2, 3], 7)'],
    'fa24-q4-c': ['semisums(6)', 'semisums(12)', 'semisums(7)'],
    'fa24-q4-c-blank-l': ['primitive_semiperfect(6)', 'primitive_semiperfect(12)', 'primitive_semiperfect(28)', 'primitive_semiperfect(7)'],
    'fa24-q5-a': ['longer((), ())', 'print(longer(Link(1), Link(2)))', 'print(longer((), Link(5)))', 'print(longer(Link(1, Link(2, Link(3))), Link(4, Link(5))))'],
    'fa24-q5-b': ['longest((), 5)', 'print(longest(Link(1, Link(1, Link(1))), 2))', 'print(longest(Link(3, Link(1, Link(2))), 3))', 'print(longest(Link(0, Link(0)), 0))'],
    'fa25-q4-a': ['exclude([], 1)', 'exclude([1, 1, 1], 1)', 'exclude([1, 2, 3], 4)', 'a = [2, 1, 2]\nexclude(a, 2), a'],
    'fa25-q4-b': ['exclude_link((), 1)', 'exclude_link(Link(1, Link(1)), 1)', 'print(exclude_link(Link(1, Link(2, Link(1, Link(3)))), 1))',
                  'a = Link(2, Link(1))\nb = exclude_link(a, 2)\nprint(a); print(b)'],
    'fa25-q6-a': ['symmetrical({})', "symmetrical({'A': 'A'})", "symmetrical({'A': 'B'})", "symmetrical({'A': 'B', 'B': 'A', 'C': 'D', 'D': 'C'})"],
    'fa25-q6-b': ['acceptable("M")', 'acceptable("MP")', 'acceptable("M_P_")', "acceptable(\"AB\", {'A': 'B', 'B': 'A'})", "acceptable(\"AAB_\", {'A': 'B', 'B': 'A'})"],
    'fa25-q6-c': ['count_pizzas(3)', 'count_pizzas(4)', 'count_pizzas(6)'],
    'fa25-q6-d': ['pizzas(3)', 'len(pizzas(5))', 'pizzas(2, False)', 'len(pizzas(4, False))'],
    'sp15-q3-d': ['print(double_up(Link(5)))', 'print(double_up(Link(1, Link(2, Link(3)))))', 's = Link(7, Link(8))\ndouble_up(s)\nprint(s)'],
    'sp15-q4-b': ["decrypt('', {'a': 'x'})", "decrypt('ab', {'a': 'x'})", "decrypt('aab', {'a': 'x', 'aa': 'y', 'b': 'z', 'ab': 'w'})"],
    'sp16-q3-a': ['print(double1(Link(1)))', 'print(double1(Link(2, Link(3))))', 'print(double1(Link(1, Link(1, Link(5, Link(1))))))'],
    'sp18-q3-a': ['column([[1]], 0)', 'column([[1, 2], [3, 4]], 1)', 'column([], 0)'],
    'sp18-q3-b': ['print_grid([[1]])', 'print_grid([[5, 100], [-1, 7]])', 'print_grid([[1, 22, 333]])'],
    'sp18-q3-c': ['expand([[1]], 1, 1, 0)', 'expand([[1]], 2, 3, 9)', 'expand([], 2, 2, 0)', 'g = [[1, 2]]\nexpand(g, 2, 3, 0)\ng'],
    'sp18-q4-a': ['print(stretch(Link(1)))', 'print(stretch(Link(1, Link(2))))', 'print(stretch(Link(1, Link(2, Link(3))), 1))'],
    'sp18-q4-b': ['combo(1, 1)', 'combo(12, 21)', 'combo(123, 456)', 'combo(5, 55)'],
    'sp19-q3': ['in_nested(1, [])', 'in_nested(1, [[[]]])', 'in_nested(3, [1, [2, [3]]])', 'in_nested([2], [1, [2]])'],
    'sp20-q2-a': ['is_power(2, 1)', 'is_power(2, 64)', 'is_power(3, 10)', 'is_power(10, 1000)', 'is_power(4, 2)'],
    'sp20-q2-b': ['sorted(powers(1, 2))', 'sorted(powers(1248, 2))', 'sorted(powers(8421, 2))', 'sorted(powers(39, 3))'],
    'sp20-q3-a': ['sum_link((), abs)', 'sum_link(Link(-2, Link(3)), abs)', 'sum_link(Link(1, Link(2, Link(3))), lambda x: x * x)'],
    'sp21-q4': ['print(separate(0, Link(5, Link(5, Link(6, Link(6))))))', 'print(separate(0, Link(5, Link(6, Link(5)))))', 'print(separate(0, Link(0, Link(0))))'],
    'sp21-q6-b-c': ['a = make_source("A", 10, 2, 1, hours=3)\nb = make_source("B", 1, 5, 2, hours=2)\ncalc_emissions([a, b], "carbon dioxide")',
                    'a = make_source("A", 10, 2, 1, hours=3)\nb = make_source("B", 1, 5, 2, hours=2)\ncalc_max_source([a, b], "methane")',
                    'calc_emissions([], "methane")'],
    'sp21-q7': ['print(PaperReam("blue", 5))', "print(PaperReam('it\\'s', 0))", 'PaperReam("x", 1) == PaperReam("x", 1)'],
    'sp22-q1-c': ['flatten([])', 'flatten([[], [[]]])', 'flatten([1, [2, [3, [4]]], 5])', 'flatten([[1, 2], 3])'],
    'sp22-q3': ['print(DictionaryEntry("a", "b"))', 'str(DictionaryEntry("cat", "a pet"))', 'DictionaryEntry("x", "y")'],
    'sp22-q4': ['print(make_necklace(["a"], 1))', 'print(make_necklace(["a", "b", "c"], 2))', 'b = ["x", "y"]\nmake_necklace(b, 5)\nb'],
    'sp22-q8-c': ['p = HoopPlayer(None, 3)\nq = HoopPlayer(None, 3)\nget_scores_except([p, q], p)',
                  'p = HoopPlayer(None, 1)\nget_scores_except([p], p)',
                  'p, q, r = HoopPlayer(None, 1), HoopPlayer(None, 2), HoopPlayer(None, 1)\nget_scores_except([p, q, r], q)'],
    'sp22-q8-d': ['roll_dice(make_test_dice([1]), 1)', 'roll_dice(make_test_dice([3, 1, 4]), 2)', 'roll_dice(make_test_dice([2, 3]), 5)',
                  'd = make_test_dice([2, 1, 6])\nroll_dice(d, 1), roll_dice(d, 2)'],
    'sp23-q3-a': ['prefix([])', 'prefix([5])', 'prefix([-1, -1, 2])'],
    'sp23-q3-b': ['tens(Link(10))', 'tens(Link(5, Link(5, Link(5, Link(5)))))', 'tens(Link(1, Link(2, Link(3, Link(4)))))'],
    'sp23-q5-a': ['count_park(0)', 'count_park(3)', 'count_park(5)'],
    'sp23-q5-b': ['sorted(park(0))', 'sorted(park(3))', 'len(park(5))'],
    'sp23-q5-c': ['sorted(pack(1))', 'sorted(pack(2))', 'sorted(pack(6))', 'len(pack(8))'],
    'sp24-q4-a': ['is_strip([])', 'is_strip([7])', 'is_strip([1, 3])', 'is_strip([5, 6, 7, 9])', 'is_strip([2, 1])'],
    'sp24-q4-b': ['drip([], [1, 2])', 'drip([1], [2])', 'drip([2], [1])', 'drip([1, 2], [3, 4])', 'drip([1, 3], [2, 5])'],
    'sp24-q4-c': ['longest([])', 'longest([5])', 'longest([3, 1, 2, 3])', 'longest([9, 8, 7])', 'longest([1, 5, 2, 6, 3, 7, 4])'],
    'sp25-q5-a': ['muladd(Link(3, Link(4)))', 'muladd(Link(1, Link(2, Link(3))))', 'muladd(Link(2, Link(2, Link(2, Link(2)))))'],
    'sp25-q5-b': ['ways(0, 3)', 'ways(1, 1)', 'ways(3, 5)', 'ways(1, 6)'],
    'sp25-q5-c': ['close([5], 3)', 'close([2, 3], 6)', 'close([2, 3], 0)', 'close([1, 1, 1], 2)', 'close([2, 5, 1, 3], 100)'],
    'sp25-q5-d': ['close_exp([5], 3)', 'close_exp([2, 3], 6)', 'close_exp([2, 3], 0)', 'close_exp([2, 5, 1, 3], 100)'],
    'sp26-q7': ['circle(1, 2)', 'circle(0, 3)', 'earring(1, [1, 1])', 'earring(4, [3, 3])', 'earring(6, [2, 1, 3])'],
    'sp26-q8': ['convert([7])', 'print(convert([[1], [2]]))', 'print(convert([1, [2, [3]], []]))'],
    'su20-q2': ["schedule('', 0, 9)", "schedule('5', 5, 1)", "schedule('??', 3, 2)", "schedule('?0?', 18, 9)"],
    'su20-q3-microscope': ['p, x = microscope()(5)\nx', 'p = microscope(10, 1)\np, x = p(1)\np, y = p(2)\np, z = p(3)\n(x, y, z)'],
    'su20-q3-plush': ['plush(microscope(), [7])', 'plush(microscope(), [1, 1, 1, 1])', 'plush(microscope(5, -1), [2, 3])'],
    'su20-q5': ['subsaltshaker(5)', 'subsaltshaker(12)', 'subsaltshaker(33333)', 'subsaltshaker(1223334444)'],
    'su20-q6': ['copycat([], [])', "copycat(['x'], [0])", "copycat(['a', 'b'], [2, -1])", "copycat(['a', 'b', 'c'], [2, 2, -3])"],
    'su21-q2-a': ['from operator import add, sub\no = order_order([sub])\no = o(5, 2)\no = o(1, 1)',
                  'from operator import add, mul\no = order_order([mul, add])\no = o(3, 3)\no = o(3, 3)\no = o(2, 2)'],
    'su21-q2-b': ['list_skipper([4])', 'list_skipper([2, 1])', 'list_skipper([3, 1, 2, 4])'],
    'su21-q4': ['max_exp([1, 5])', 'max_exp([2, 2, 2])', 'max_exp([1, 1, 1])', 'max_exp([2, 1, 3])'],
    'su21-q5-b': ['a = add_seen_d(1)\na = a(2)\na = a(2)\na = a(5)', 'a = add_seen_d(3)\na = a(1)\na = a(1)\na = a(1)\na = a(1)'],
    'su22-q3-a': ['inverse_checker(lambda x: x * 2, lambda x: x // 2)(5)', 'inverse_checker(lambda x: x * 2, lambda x: x * 2)(1)',
                  'inverse_checker(abs, lambda x: x)(-3)', 'inverse_checker(abs, lambda x: x)(3)'],
    'su22-q3-b': ['force_truthy(lambda x: x)(0)', 'force_truthy(lambda x: x)(5)', "force_truthy(lambda x: '')(3)", 'force_truthy(lambda x: [])(1)'],
    'su22-q4': ['least_resistance(0, 0, lambda x, y: 7)', 'least_resistance(1, 0, lambda x, y: 1)', 'least_resistance(2, 2, lambda x, y: x)',
                'least_resistance(3, 2, lambda x, y: (x - y) ** 2)'],
    'su22-q5': ['from operator import mul\ncond_curry(mul, lambda x: x > 0)(-1)(3)(-2)(4)', 'from operator import sub\ncond_curry(sub, lambda x: x % 2)(2)(4)(9)(6)(3)'],
    'su22-q6-a': ['count_digits(5)', 'count_digits(10)', 'count_digits(1000000)'],
    'su22-q6-b': ['blob_sum(5, 5)', 'blob_sum(12, 12)', 'blob_sum(1111, 22)', 'blob_sum(1111, 112)', 'blob_sum(406, 10)'],
    'su22-q8-b': ["more_sold([Boba('A', 1, True, 'x')], [Coffee('B', 1, True)], {'A': 3, 'B': 1})",
                  "more_sold([], [], {})", "more_sold([Boba('A', 1, True, 'x')], [Coffee('B', 1, True)], {'A': 2, 'B': 2})"],
    'su23-q3-a': ['digit_widget(3)(333)', 'digit_widget(0)(10203)', 'digit_widget(9)(1234)', 'digit_widget(1)(0)'],
    'su23-q3-b': ['digit_widget_iter(3)(333)', 'digit_widget_iter(0)(10203)', 'digit_widget_iter(9)(1234)', 'digit_widget_iter(1)(0)'],
    'su23-q3-c': ['digit_machine(0)', 'digit_machine(4)', 'digit_machine(1489)', 'digit_machine(8040)'],
    'su23-q4': ['goatda(lambda x: x * 2, 0)(5)', 'goatda(lambda x: x * 2, 5)(1)', 'goatda(lambda x: x - 1, 1)(0)'],
    'su23-q5-a': ['donut_tower(3, 1)', 'donut_tower(2, 2)', 'donut_tower(10, 1)', 'donut_tower(100, 4)'],
    'su23-q5-b': ['alternating_tower(0, 100, 1)', 'alternating_tower(3, 0, 1)', 'alternating_tower(100, 100, 1)', 'alternating_tower(20, 2, 2)'],
    'su23-q5-c': ['sweetest_tower(0, 0, 1)', 'sweetest_tower(3, 0, 1)', 'sweetest_tower(100, 100, 1)', 'sweetest_tower(9, 8, 2)'],
    'su24-q4-a': ['add_consecutive(5)', 'add_consecutive(11)', 'add_consecutive(987)', 'add_consecutive(1213)'],
    'su24-q4-b': ['add_consecutive(5)', 'add_consecutive(11)', 'add_consecutive(987)', 'add_consecutive(1213)'],
    'su24-q6': ['multi_compose([], 4, 4)(9)', 'multi_compose([], 1, 2)', 'multi_compose([lambda x: x + 1], 1, 2)(10)',
                'f = multi_compose([lambda x: x * 3, lambda x: x + 1, lambda x: x * 3], 1, 12)\nf(1)'],
    'su25-q3-a': ['python(5, 5)', 'python(123, 9)', 'python(1010101, 1)', 'python(11, 1)'],
    'su25-q3-b': ['longest_python(7)', 'longest_python(1111)', 'longest_python(3030303)'],
    'su25-q4-a': ['is_valid(1)', 'is_valid(24)', 'is_valid(1234)', 'is_valid(3412)', 'is_valid(1324)'],
    'su25-q4-b': ['valid_subseq(1)', 'valid_subseq(21)', 'valid_subseq(1324)'],
}
